#---------------------------------------------------#
## 更新：2020-03-24
## 链接：https://lolico.me/subscribe/Clash/UnblockNeteaseMusic.yaml
#---------------------------------------------------#

# HTTP 代理端口
port: 7890 

# SOCKS5 代理端口
socks-port: 7891 

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892 

# 允许局域网的连接
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: '' 

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

Proxy:
  - name: 🎵 解锁节点1
    type: ss
    server: music.desperadoj.com
    port: 30001
    cipher: aes-128-gcm
    password: desperadoj.com
  - name: 🎵 解锁节点2
    type: http
    server: 106.52.127.72
    port: 19951
  - name: 🎵 解锁节点3
    type: http
    server: music.griouges.cn
    port: 39000

Proxy Group:
  - name: 🎸解锁网易云音乐
    type: select
    proxies:
      - 🎵 解锁节点1
      - 🎵 解锁节点2
      - 🎵 解锁节点3
      - DIRECT

Rule:
  # Netease Music
  - DOMAIN,api.iplay.163.com,🎸解锁网易云音乐
  - DOMAIN,apm3.music.163.com,🎸解锁网易云音乐
  - DOMAIN,apm.music.163.com,🎸解锁网易云音乐
  - DOMAIN,interface3.music.163.com,🎸解锁网易云音乐
  - DOMAIN,interface.music.163.com,🎸解锁网易云音乐
  - DOMAIN,music.163.com,🎸解锁网易云音乐
  - IP-CIDR,39.105.63.80/32,🎸解锁网易云音乐
  - IP-CIDR,45.254.48.1/32,🎸解锁网易云音乐
  - IP-CIDR,47.100.127.239/32,🎸解锁网易云音乐
  - IP-CIDR,59.111.160.195/32,🎸解锁网易云音乐
  - IP-CIDR,59.111.160.197/32,🎸解锁网易云音乐
  - IP-CIDR,59.111.181.35/32,🎸解锁网易云音乐
  - IP-CIDR,59.111.181.38/32,🎸解锁网易云音乐
  - IP-CIDR,59.111.181.60/32,🎸解锁网易云音乐
  - IP-CIDR,101.71.154.241/32,🎸解锁网易云音乐
  - IP-CIDR,103.126.92.132/32,🎸解锁网易云音乐
  - IP-CIDR,103.126.92.133/32,🎸解锁网易云音乐
  - IP-CIDR,112.13.119.17/32,🎸解锁网易云音乐
  - IP-CIDR,112.13.122.1/32,🎸解锁网易云音乐
  - IP-CIDR,115.236.118.33/32,🎸解锁网易云音乐
  - IP-CIDR,115.236.121.1/32,🎸解锁网易云音乐
  - IP-CIDR,118.24.63.156/32,🎸解锁网易云音乐
  - IP-CIDR,193.112.159.225/32,🎸解锁网易云音乐
  - IP-CIDR,223.252.199.66/32,🎸解锁网易云音乐
  - IP-CIDR,223.252.199.67/32,🎸解锁网易云音乐

  # Netease Music Advertising
  - DOMAIN,admusicpic.music.126.net,REJECT
  - DOMAIN,iadmat.nosdn.127.net,REJECT
  - DOMAIN,iadmusicmat.music.126.net,REJECT
  - DOMAIN,iadmusicmatvideo.music.126.net,REJECT

  # Final
  - MATCH,DIRECT